# Generated by Django 3.2.20 on 2023-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(blank=True, default=False, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('token', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Токен авторизации')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Аватарка')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Статус блокировки')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('sms_code', models.IntegerField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
