# Generated by Django 3.2.20 on 2023-08-15 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название медитации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('duration', models.DurationField(verbose_name='Длительность медитации')),
                ('completed_by_users', models.ManyToManyField(blank=True, related_name='completed_meditations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
