# Generated by Django 3.2.20 on 2023-08-15 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('date_add_tokens', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления токенов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кошелек пользователя')),
            ],
            options={
                'verbose_name': 'Баланс токенов пользователя',
                'verbose_name_plural': 'Баланс токенов пользователей',
                'db_table': 'wallet_tokens',
            },
        ),
    ]
