# Generated by Django 3.2.20 on 2023-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField(unique=True, verbose_name='Номер страницы')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('content', models.TextField(verbose_name='Содержание страницы')),
            ],
            options={
                'verbose_name': 'Текст Онбординга',
                'verbose_name_plural': 'Тексты Онбординга',
            },
        ),
    ]
