# Generated by Django 3.2.20 on 2023-08-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_administrator_chatmessage_complaint_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
